###set Role
POST http://localhost:4500/users/role/dc66b82a-b996-40e3-a387-1d9a213f95d3
Content-Type: application/json

{
  "role":"customer"
}
### register user
POST http://localhost:4500/users/register
Content-Type: application/json

# {
#   "Name": " Sharon Cherotich ",
#   "email": "sharoncherotich112@gmail.com",
#   "password": "Strong@Password123",
#   "role":"customer"
# }

{
  "Name": "Duncan Kingangi",
  "email": "kingangiduncan47@gmail.com",
  "password": "Duncun@123",
  "role":"Specialist"
}


### validate user
PUT http://localhost:4500/users/validate/aaaecb53-2d2a-406a-9630-2135a087b8d9
Content-Type: application/json

{
  "OTP": "4235"  
}


### login user
POST http://localhost:4500/users/login
Content-Type: application/json

{
   "email":"kingangiduncan47@gmail.com",
  "password": "Duncun@123"
}

### Get all Users
GET  http://localhost:4500/users
Content-Type: application/json
 

### One user details
GET http://localhost:4500/users/267d74d3-0977-467f-9485-d78b343b42d5
Content-Type: application/json

### Delete user
DELETE http://localhost:4500/users/delete/55a4c7f2-e529-42f9-a624-0fc824f3ae54

 
### Industries
# Create industry
POST  http://localhost:4500/industry
Content-Type: application/json

{
"industryName":"Education",
"industryImage":"this is an image"
}
 
### getAll industries
GET http://localhost:4500/industry/
Content-Type: application/json

### getOne
GET http://localhost:4500/industry/baacb12b-90c6-4661-bc28-641932a35234
 
### Delete industry
DELETE   http://localhost:4500/industy/f4981088-9310-4235-ac3d-98a6a009131c
Content-Type: application/json
 
 
###Sectors section

#create a sector
POST  http://localhost:4500/sector/create
Content-Type: application/json

{
"sectorName":"Nurse",
"industryID":"04f513cb-bf34-4b6c-bc3e-521d6894f7f3"
}
 
### Get sector by industry
GET http://localhost:4500/sector/04f513cb-bf34-4b6c-bc3e-521d6894f7f3
Content-Type: application/json

