###set Role
POST http://localhost:4500/users/role/dc66b82a-b996-40e3-a387-1d9a213f95d3
Content-Type: application/json

{
  "role":"customer"
}
### register user
POST http://localhost:4500/users/register
Content-Type: application/json

# {
#   "Name": " Sharon Cherotich ",
#   "email": "sharoncherotich112@gmail.com",
#   "password": "Strong@Password123",
#   "role":"customer"
# }

{
  "Name": " Jane Ngene",
  "email": "janengene12@gmail.com",
  "password": "Jane@1234",
  "role":"customer"
}


### validate user
PUT http://localhost:4500/users/validate
Content-Type: application/json

{
  "userID": "ebedb25d-4db6-41ac-9b37-0a8ce0c375c5",
  "OTP": "8405"  
}


### login user
POST http://localhost:4500/users/login
Content-Type: application/json

# {
#     "email":"janengene12@gmail.com",
#     "password":"12345"
# }

{
  "email": "chombasheila980@gmail.com",
  "password": "StrongPassword123"
}

### Get all Users
GET  http://localhost:4500/users
Content-Type: application/json
 

### One user details
GET http://localhost:4500/users/dc66b82a-b996-40e3-a387-1d9a213f95d3
Content-Type: application/json

### Delete user
DELETE http://localhost:4500/users/delete/dc66b82a-b996-40e3-a387-1d9a213f95d3

 
### Industries
# Create industry
POST  http://localhost:4500/industry
Content-Type: application/json

{
"industryName":"Education",
"industryImage":"this is an image"
}
 
### getAll
GET http://localhost:4500/industry/
Content-Type: application/json

### getOne
GET http://localhost:4500/industry/baacb12b-90c6-4661-bc28-641932a35234
 
### Delete industry
DELETE   http://localhost:4500/industy/f4981088-9310-4235-ac3d-98a6a009131c
Content-Type: application/json
 
 
###Sectors section

#create a sector
POST  http://localhost:4500/sector/create
Content-Type: application/json

{
"sectorName":"QAQE",
"industryID":"baacb12b-90c6-4661-bc28-641932a35234"
}
 
### Get sector by industry
GET http://localhost:4500/sector/baacb12b-90c6-4661-bc28-641932a35234
Content-Type: application/json

