
### Industries
# Create industry
POST  http://localhost:4500/industry
Content-Type: application/json

{
"industryName":"Education",
"industryImage":"this is an image"
}
 
### getAll industries
GET http://localhost:4500/industry/
Content-Type: application/json

### getOne
GET http://localhost:4500/industry/baacb12b-90c6-4661-bc28-641932a35234
 
### Delete industry
DELETE   http://localhost:4500/industy/f4981088-9310-4235-ac3d-98a6a009131c
Content-Type: application/json
 
 
###Sectors section

#create a sector
POST  http://localhost:4500/sector/create
Content-Type: application/json

# {
# "sectorName":"Nurse",
# "industryID":"04f513cb-bf34-4b6c-bc3e-521d6894f7f3"
# }

{
"sectorName":"MUSIC TUTOR",
"industryID":"b83c0ed7-2df5-431c-872b-2aee755bf0b8"
}
 
### Get sector by industry
GET http://localhost:4500/sector/04f513cb-bf34-4b6c-bc3e-521d6894f7f3
Content-Type: application/json







### create gig
POST http://localhost:4500/gigs/create/3bd6e83c-cc2a-4532-8121-44ef3d7788ad
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI0YWZiMTlkNC02NDk2LTQwYTUtYWE2OC0zYmMyMGI3NjNlZGEiLCJOYW1lIjoiIEphbmUgTmdlbmUiLCJlbWFpbCI6ImphbmVuZ2VuZTEyQGdtYWlsLmNvbSIsInBob25lX251bWJlciI6bnVsbCwiRE9CIjpudWxsLCJnZW5kZXIiOm51bGwsImVkdWNhdGlvbiI6bnVsbCwiZXhwZXJpZW5jZSI6bnVsbCwibGFuZ3VhZ2UiOm51bGwsImFib3V0IjpudWxsLCJuaWNrbmFtZSI6bnVsbCwiY291bnRyeSI6bnVsbCwiY2l0eSI6bnVsbCwiaW5kdXN0cnkiOm51bGwsInByb2ZpbGVfcGljIjpudWxsLCJPVFAiOiIkMmIkMDQkN1ZhTi82a0d5cTI5ZGRyUlphSU11ZWw4ZG5uVUV4QUVwdGdFV2JNRllIVlJod0Uua0JnR0MiLCJyb2xlIjoiYWRtaW4iLCJ3ZWxjb21lZCI6dHJ1ZSwiaXNWZXJpZmllZCI6dHJ1ZSwicHJvZmlsZV9pZCI6bnVsbCwic2VjdG9yIjpudWxsLCJpYXQiOjE3MTEyODIwNjUsImV4cCI6MTg0MDg4MjA2NX0.fWh4mpuWgo9k5urr9OiN1NICt-NenVJIiSaYnEAaqmA

{
"gigName": "I will aloot ",  
"gigImage":"https://www.freepik.com/education-learning#from_element=photos_categories_block.png",
"gigDescription": "I will offer you these services",
"rate" :"$15/hour"
}

### get all gigs
GET http://localhost:4500/gigs
Content-Type: application/json

### get gig by gigid
GET http://localhost:4500/gigs/9f9c1cbc-0b8c-4fed-8231-b52523e727e1

### get gig by userID
GET http://localhost:4500/gigs/user/9f9c1cbc-0b8c-4fed-8231-b52523e727e1
Content-Type: application/json


### FILTER GIGS BY INDUSTRY
GET http://localhost:4500/gigs/b83c0ed7-2df5-431c-872b-2aee755bf0b8
Content-Type:application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI0YWZiMTlkNC02NDk2LTQwYTUtYWE2OC0zYmMyMGI3NjNlZGEiLCJOYW1lIjoiIEphbmUgTmdlbmUiLCJlbWFpbCI6ImphbmVuZ2VuZTEyQGdtYWlsLmNvbSIsInBob25lX251bWJlciI6bnVsbCwiRE9CIjpudWxsLCJnZW5kZXIiOm51bGwsImVkdWNhdGlvbiI6bnVsbCwiZXhwZXJpZW5jZSI6bnVsbCwibGFuZ3VhZ2UiOm51bGwsImFib3V0IjpudWxsLCJuaWNrbmFtZSI6bnVsbCwiY291bnRyeSI6bnVsbCwiY2l0eSI6bnVsbCwiaW5kdXN0cnkiOm51bGwsInByb2ZpbGVfcGljIjpudWxsLCJPVFAiOiIkMmIkMDQkN1ZhTi82a0d5cTI5ZGRyUlphSU11ZWw4ZG5uVUV4QUVwdGdFV2JNRllIVlJod0Uua0JnR0MiLCJyb2xlIjoiYWRtaW4iLCJ3ZWxjb21lZCI6dHJ1ZSwiaXNWZXJpZmllZCI6dHJ1ZSwicHJvZmlsZV9pZCI6bnVsbCwic2VjdG9yIjpudWxsLCJpYXQiOjE3MTEyNTg0MjIsImV4cCI6MTg0MDg1ODQyMn0.ntA8cz84eEFV3uUWVccf0K5yXEukkaYa3d7XSnXTM9g
