
### create gig
POST http://localhost:4500/gigs/create
Content-Type: application/json

{
"gigName": "Testing Gig ",  
"gigImage":"image will go here",
"gigDescription": "I will offer you these services",
"rate" :"$15/hour",
"userID":"aaaecb53-2d2a-406a-9630-2135a087b8d9"
}

### get all gigs
GET http://localhost:4500/gigs
Content-Type: application/json

### get gig by id
GET http://localhost:4500/gigs/09283830-9409-46a7-a6da-834f5a06e997
Content-Type: application/json