### register user
POST http://localhost:4500/users/register
Content-Type: application/json

{
  "Name": " Sharon Cherotich ",
  "email": "sharoncherotich112@gmail.com",
  "password": "StrongPassword123"
}


### validate user
PUT http://localhost:4500/users/validate
Content-Type: application/json

{
  "userID": "ebedb25d-4db6-41ac-9b37-0a8ce0c375c5",
  "OTP": "8405"  
}


### login user
POST http://localhost:4500/users/login
Content-Type: application/json

# {
#     "email":"janengene12@gmail.com",
#     "password":"12345"
# }

{
  "email": "chombasheila980@gmail.com",
  "password": "StrongPassword123"
}

### Get all Users
GET  http://localhost:4500/users
Content-Type: application/json
 
### Delete user
DELETE http://localhost:4500/users/delete/5af88f03-7c21-41de-819a-a340105a69c1

 
### Products
GET  http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f629760
Content-Type: application/json
 
 
###
DELETE   http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f6297606b66
Content-Type: application/json
 
 

